### ISSUE TITLE
[Epic] Refactor code according to new DW structure

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#110]
* [x] Change fixture data to be inline with new DW structure
* [x] Plan how do we do this ...
  * three option:
    * Import reasonably little chunk (Eg: latest month or two) of actuall data from RDS
    * Modify existing python code to create simmilar fixture data
    * Combination of those two: export little chunk to fixtures dir and load with python script to local db
 * [x] Implement
  * [x] steps:
    *  Get real data from RDS for whole August into count.csv
    * Place count.csv, and reference data into `tests/fixtures/data` dir (16 MB total) (can we get < 4MB)
    * Modify existing script to create all needed tables
    * Import data from csv files into tables and aggregate (Populate Cubes)
    * Create constraints and indexes

Later:
* [ ] Reduce size of data export (pick a random selection)
* [ ] Reuse code from aggregator directly (import?)

**Comment by zelima** [comment]
- [ ] We can sub-module [aggregator](https://github.com/cybergreen-net/aggregator) and use it's functionality. this way development database will always be up to date to RDS.
- [ ] We can use data for only 4-5 countries and 4-5 AS numbers inside. This will significantly reduce size of `count.csv` 

Moving to current milestone

**Comment by rufuspollock** [comment]
FIXED. Back in December in fact. The "later" stuff should be separate issues as follows:

Moving out "We can sub-module aggregator and use it's functionality. this way development database will always be up to date to RDS." to #206 

WONTFIX on making fixture data smaller as does not matter much.
