### ISSUE TITLE
Refactor logic layer

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#112]
* [x] Work out what we do re scores as they no longer exist in backend (do we add in logic layer or add in frontend or ...)
* [x] Identify where scores are needed? Maps only or ... 
  * [x] Identify where we are removing them
      * country list page
      * country/{id} page
      * risk/{id}
      * risk/{risk_id}/{country_id} page
  * [x] Identify where we are keeping them
      * only for maps for now
* [x] Refactor the logic layer

**Comment by zelima** [comment]
Fixed
