### ISSUE TITLE
Plan refactor for frontend JS to use React and do basic set-up

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#132]
* [x] Read React tutorials
* [x] Plan out work
* [x] Do prep and setup
  * [x] checkout new branch from master. Named `feature/react`
  * [x] Prepare webpack.config.js
  * [x] Prepare basic failing tests
    * search and decide which testing library to use? 
    * can mocha be used here? (mocha is fine IMO - unless very strong push for Jest since we already use mocha) 
    * jest? If so read some read/learn some about jest.

**Comment by zelima** [comment]
Moving to next milestone. Did not fit in time

**Comment by zelima** [comment]
FIXED new repo is set up https://github.com/cybergreen-net/cg-graphs. All basic set-ups done there
