### ISSUE TITLE
Gobal DDOS for front page

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#138]
### What we need to do

Have [stacked area graph](https://plot.ly/nodejs/filled-area-plots/) on main page showing Global DDOS

[Mockup](https://docs.google.com/drawings/d/1XUi2K5QlZJrCgO817LBat_3FDcTDHClKdAFuWzIRFfs/edit)
---

### Implementation

* [x] Write API {8}
    * [x] Write Tests for API {4}
* [x] create new repo for graphs - cg-graphs 
* [x] Prepare specifications for vega or plotly graphs handling multiple lines. {2}
* [x] Prepare data (if needed) for vizualizations {2}
    * [x] Prepare test for specifications and/or data for vizualization library.
* [x] Build react components responsible for rendering graph using specifications defined above (Irakli: think this should be sepreated into other repo and sub moduled) {16}
    * [x] Write Tests for React {8}
* [x] submodule cg-graphs int this repo and use it as middleware (for now)

**Comment by zelima** [comment]
FIXED we have stacked barchart Showing risks stacked to Total DDOS on a home page 
https://cybergreen-staging.herokuapp.com

**Comment by aaronkaplan** [comment]
Visually the second graph is the best. It has one flaw: if there is no data, it should not interpolate between the last two values.
Apart from that, it is the clearest IMHO.

Could you also please talk with @shiweiart and agree on a common color scheme for all our graphs on the stats site?

One more thing: we should not include Mirai in this graph. Because this graph is actually the "global DDOS potential based of UDP amplification attacks". Why can't we include Mirai here? Because we don't have (and will not have) a meaningful amplification factor for Mirai. So... adding it here with an assumed AF of "1" is sort of wrong.
@rufuspollock see also the discussion on this on the metrics mailing list.

Apart from that: fantastic work!! Really happy with graph number 2.

I did a quick user test if people understand it (CERTs) and yes - if you take out Mirai, they get it.
Even with graph number 1.

**Comment by rufuspollock** [comment]
@aaronkaplan the problem is that there is no easy way to have a line graph **not** interpolate between values. Our UX expert @shiweiart herself preferred the line graph but went with option 1 because of this issue with interploation -- as you noticed the missing values really mess with the graph. So your choice is:

- Graph 2: as is
- Graph: 1

**Mirai**: ok we can exclude this. One request (and we can create an issue for this). Can we have a living document that records this stuff e.g. in our docs directory in pm repo https://github.com/cybergreen-net/pm/tree/master/docs

**Comment by aaronkaplan** [comment]
good idea about the living document.
Want to start a structure ?

**Comment by aaronkaplan** [comment]
Concerning the line graph. Could you explain why this is exactly hard? Would you need to tweak some line graph library?
