### ISSUE TITLE
Refactor country page to show multiple graphs and bar charts for comperision

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#147]
## Comparative Performance

[User Sories - see doc][us]

[us]: https://docs.google.com/document/d/1TZ-q_45AsGmxU5ywSNkc6iokGFnyXtkbBSWOl75zr6I/edit#heading=h.nfqhp3yqapft

### What we need to do 

* Create multiple line graphs for each risk for given country.
* Create multiple stacked barcharts for each risk for 10 "Worst" ASNs
* Add search box for graphs, to search country on demand for comperisions

[Mock up](https://docs.google.com/drawings/d/1z3zRxIoIdOi82QbVhxoJmqBCIMTu2z4GJklNnxMecFg/edit)

### Implementation

- [x] (cg-graphs)Refactor existing react APP components to use new spec for data. And hanle multiple graphs if needed.
    * Add fixtures for a country
    * Add fixtures for asns in that country
    * define urls for fixtures data
    * Write tests for data retrieving and preparing for plots
    * Make changes to App.js component
- [x] Prepare data (or specifications) for line graphs from server side according to what react app will need
    * List of graphs to be rendered (risks)
    * List of URLs to API endpoints for graphs (Total, given counrty)
    * Type of graph (line, bar)
    * more
* [x] Prepare data for charts
    * Get fist 10 asn with most count for given country and risk
    * Dito re speifications as for line grapsh

**Comment by zelima** [comment]
FIXED https://cybergreen-staging.herokuapp.com/country/united-kingdom
possibly DUPLICATE of https://github.com/cybergreen-net/cg-graphs/issues/37 and https://github.com/cybergreen-net/stats-new/issues/161
