### ISSUE TITLE
[epic][country] Source of Infection - AS bar charts

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/stats-new#161]
User Epic: As a policy maker or a National CERT I want to see for a given risk which AS are the source of that infection so that I can see who I should engage with to mitigate the risk. 

## Proposed Solution

For each risk:

* Stacked Time Series Bar chart.
* Each bar is counts for an individual AS. We only show the top ~9 AS with the most infections plus one item for all the rest.

Mock-up: RHS of the [country page mock-up][mock-up]

[mock-up]: https://docs.google.com/drawings/d/1_UqozUCgl2Ueo9vkknDmA-rjDFo64_zKVLihOxg4muc/edit

### Bar Chart Itself

UI

* [x] All the stuff in the mock-up ;-) - See https://github.com/cybergreen-net/cg-graphs/issues/37
* [x] Have search box with dropdown to jump on AS performance page https://github.com/cybergreen-net/cg-graphs/issues/42
* [x] Integrate changes into country page https://github.com/cybergreen-net/stats-new/issues/175

API

* [x] List of AS for a country and risk ordered by count descending with limit and total https://github.com/cybergreen-net/stats-new/issues/169

**Redux store structure / API results ...**
```javascript=
[
  {
    country: "GB"
    risk: ...
    date: ...
    granularity: ...
    count: ...
    count_normalized:
    count_amplified: ...
    as: [
      {
        id: 192
        count: 500
        count_amplified: ...
      },
      {
        id: 254,
        count: 550
        count_amplified: ...
      },
      ...
    ]
  }
]
```

### Entire Page

* [x] Repeat bar chart for each risk
* [x] Get nice layout (row of country performance and this source item together)
* [ ] Under each graph a: see all ASs => links to the AS page
  * this needs the page to be impelented first
* [x] Jump to ASN at top of the page

**Comment by zelima** [comment]
FIXED and deployed https://cybergreen-staging.herokuapp.com/country/united-kingdom
