### ISSUE TITLE
Integrate UI changes on the AS page

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#165]
## Tasks

- [x] Update submodule (`index.min.js`) in `public/static/vendor/cg-graphs`
- [x] pass all necessary variables from server 
  - Eg: `ASPerformanceViews` 
  - Anything else if needed
- [x] deploy on staging

**Comment by zelima** [comment]
FIXED UI changes integrated  http://localhost:5000/country/united-kingdom/asn/5413
