### ISSUE TITLE
[Epic] ranking for countries

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#194]
User epic: How is Everyone Doing?

See [user stories](https://docs.google.com/document/d/1TZ-q_45AsGmxU5ywSNkc6iokGFnyXtkbBSWOl75zr6I/edit#heading=h.7c3jfspnbuos):

## Proposed solution

- [x] have a rank indicated on county performance page above each graph on LHS
- [x] on country page show ranked (order should be fixed and not change with sorting) (TBC)

## Tasks 

- [x] API for ranks #155 
- [x] UI https://github.com/cybergreen-net/cg-graphs/issues/70
- [x] on `country`  page add new column "rank"
  - Should be ranked by `ddos` ???
  - order should be fixed and not change with sorting. 
    - what does this exactly mean???

**Comment by zelima** [comment]
FIXED. in https://github.com/cybergreen-net/stats-new/pulls

Problem is that ranks are not really ranks but row numbers, and this may confuse the user, so for now we will hide the ranks

See example

![image](https://cloud.githubusercontent.com/assets/15143785/23561832/67ce6270-0059-11e7-96b2-d067b43a619e.png)

- sorted by ddos in ascending order

![image](https://cloud.githubusercontent.com/assets/15143785/23561872/9f160a1c-0059-11e7-8f64-3b2e26434dca.png)

**Comment by aaronkaplan** [comment]
Well , for a given risk (a column that we sort by), we somehow need the rank of a country
I understand the difference row number vs. rank . But... it's really part of the spec. So somehow we will need it.

**Comment by rufuspollock** [comment]
@aaronkaplan we discussed with Yurie and this can be post 15th (so no urgency). We agree to do something the question is **what**. We've already tried a couple of options and they have not worked well UX wise. We can try some more.

**Comment by zelima** [comment]
Closing as FIXED.
For further discussions and solution follow up #259
