### ISSUE TITLE
[epic] Improve download page 

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#198]
- [x] Update current documentation
- [x] fix download links 
- [x] Link to new [api docs](https://cybergreen-staging.herokuapp.com/api-docs/#/default)  - Or embed them if possible 
  - changed `default` to something meaningful tag Eg: `Reference data`, `Count`, `Ranking`  https://github.com/cybergreen-net/stats-new/issues/221
  - remove `/api-docs` endpoint
* [x] heading for download page should be download & API
* [x] have sections **bulk** and **API**

Mock up 
![image](https://cloud.githubusercontent.com/assets/15143785/23607155/3037595e-027d-11e7-84f1-fca857bfe653.png)

**Comment by rufuspollock** [comment]
@zelima maybe worth doing a quick mockup in google docs. Also can you check whether we can embed swagger and how hard.

**Comment by rufuspollock** [comment]
@zelima this looks good. Only comment re swagger stuff is that we should make it obvious what the endpoint is and links to specific API points should be obvious too.

**Comment by zelima** [comment]
Download link does not work

**Comment by zelima** [comment]
FIXED. download links now pointing at AWS bucket directly instead of http://bits.cybergreen.net/

FIxing http://bits.cybergreen.net/ moved as separate issue #226

**Comment by zelima** [comment]
Some tidy-up and improvement 

* [ ] heading for download page should be download & API
* [ ] have sections **bulk** and **API**

**Comment by zelima** [comment]
FIXED - Bulk and API downloads separated into sections
