### ISSUE TITLE
[Epic] Tidy-up "old" pages for 15 March 2017 release

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#199]
- [x] /asn/ - keep, useful info about what ASN is 
  - [x] Get rid of "link" column and just link the country name 
- [x] /risk/ - Keep (With up to date description)
  - [x] Delete "total devices" column
  - [x] Delete ":" at end of Overview of Risks in title
- [x] /risk/id/ - change
  - [x] remove map
  - [x] remove table
  - [x] next: show time series graph (like as or country performance) but just with global as the only default column https://github.com/cybergreen-net/cg-graphs/issues/65
- [ ] /country/ - https://github.com/cybergreen-net/stats-new/issues/204
- [x] /country/country_id/risk_id - remove as this is not usefull at all - displays only number of infected devises in given country for given risk
- [x] /about/ - keep
- [x] /vis/map/embed - remove
- [x] /data/geo.json - remove

**Comment by zelima** [comment]
FIXED see 
- https://cybergreen-staging.herokuapp.com/country 
- https://cybergreen-staging.herokuapp.com/risk
- https://cybergreen-staging.herokuapp.com/risk/openntp

**Comment by rufuspollock** [comment]
@zelima good work. Some comments:

Country page:

* [ ] DDOS numbers look like they have not been scaled to TBits/s
* [ ] I think having numbers in same column at different amounts e.g. some in k and some in m is confusing and goes against our intuitive perception based on the number of digits in a number. I'd suggest we convert everything to k.
  * [ ] I'd also suggest right justifying the number in the column
  * [ ] I'd also suggest removing the scale (e.g. k or TBits/s) into the column title so the rows themselves have pure numbers.
