### ISSUE TITLE
Misc UX and minor issues for 15 March 2017 Release

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/stats-new#200]
* [x] increase space between selector and header on home page
* [x] make rank red on country performance page
* [x] on risk/{id} page put title in green (same as on ohter pages)
  - [ ] make global dispensary when disselected 
* [x] fix slow performance https://github.com/cybergreen-net/stats-new/issues/210
* [ ] wrong favicon . See #255 
* [x] Graphs and selector improvements https://github.com/cybergreen-net/cg-graphs/issues/72
* [x] Delete statistics link in navbar #196 
* [x] 404 items
  * [x] 404 template #90
  * [x] non-existent pages do not return 404 but something else #193 
* [x] API
  * [x] cast bigint strings to ints in API #192 
  * [ ] ~~API count returns risk id not risk name - #121~~ not in this sprint
* [x] Bugs
  * [x] Safari browser and Object.values - https://github.com/cybergreen-net/cg-graphs/issues/33
* [x] map
  * [x] make map really big - like full-width of screen and appropriately high
  * [x] Heading should be same style as Global DDOS above (remove it from the plotly graph part and put in HTML)
  * [x] Colour: do we want it to change for different risks? What is the right colour?
  * [x] Title and description need along with explanation of the scale -- probably part of #205 
  * [x] units for map #237 
  * [ ] map: can we have a color gradient (like we had before in the BETA-1 map)? It's easier to distinguish different levels/ranks of the countries. Like this it's all 'red in red'.

**Comment by rufuspollock** [comment]
FIXED. All done! Well done everybody!

**Comment by aaronkaplan** [comment]
Re-opening. See #210

**Comment by aaronkaplan** [comment]
I do not see that the map is "really big" (like fullscreen). unselected this.

**Comment by zelima** [comment]
FIXED map is strached

**Comment by aaronkaplan** [comment]
Please use color gradients. Thanks. That's a customer request.
