### ISSUE TITLE
[ux] Language and explanations across stats site

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/stats-new#205]
Variety of issues with language used across site:

* Missing content: e.g. Mirai description for http://cybergreen-staging.herokuapp.com/risk
* A new user would struggle to understand acronyms (e.g. ASN, Open NTP) and key terms e.g. "counts" (counts of what?)
* Lots of grammar / typos / incomplete sentences e.g. http://cybergreen-staging.herokuapp.com/asn has "A Autonomous System" in the second sentence

## Tasks

* [x] Review every page and identify areas to improve / change https://docs.google.com/presentation/d/1-6_BxACd-Ghr-6kthWJnPttqQV4iEGRbiHNxXLTFgFs/edit
* [x] Create issues for those changes and link here - https://github.com/cybergreen-net/stats-new/issues/233
* [x] Do them all!

* [x] add glossary page under `/data` page https://github.com/cybergreen-net/www.cybergreen.net/issues/69

@zelima 

* [x] Create hackmd doc called "CyberSecurity Glossary for CyberGreen"
* [x] Create checklist of key terms / concepts e.g. Risk, and list of Risks (open ssdp), Offensive Potential, Density Metrics (copy the metrics stuff)
* [x] Make sections for these and copy existing material
* [x] Highlight missing sections with TODO

**Comment by rufuspollock** [comment]
@zelima 

* [ ] Create hackmd doc called "CyberSecurity Glossary for CyberGreen"
* [ ] Create checklist of key terms / concepts e.g. Risk, and list of Risks (open ssdp), Offensive Potential, Density Metrics (copy the metrics stuff)
* [ ] Make sections for these and copy existing material
* [ ] Highlight missing sections with TODO

**Comment by rufuspollock** [comment]
Full review yesterday with @aaronkaplan @YurieIto. We have all items captured now in deck and will move to log as issues and implement.

**Comment by zelima** [comment]
FIXED. all of this is done.
Closing as I assume we will open separate epic for glossary
