### ISSUE TITLE
[UI] Optimize site's layout for small devices

### ISSUE THREAD

**Issue by anuveyatsu** [cybergreen-net/stats-new#253]
So far the site's layout was developed for desktop computers and laptops. There are some elements showing incorrectly on the small devices. We can use bootstrap's responsive classes to fix them.

## Tasks

* [ ] Front Page `/`
  * [ ] header is not collapsible - it shows up all buttons
* [ ] Risks Page `/risk/`
  * [ ] the table is not responsive - a user cannot read all text
* [ ] Download Page `/download/`
  * [ ] API part is not responsive
* [ ] Individual country page `/country/country-id/`
  * [ ] Subheadings for columns are displayed one after another which makes unclear to what graphs they relates to
  * [ ] Graphs are not displayed correctly - taking only half of a row
  * [ ] Download buttons need to be aligned
* [ ] Individual risk page `/risk/risk-name/`
  * [ ] Radio buttons in the graph is out of the box.

**Comment by rufuspollock** [comment]
Good review. Quick comments:

* It would be to screenshot some of these items if you can to remove any ambiguity about the problem
  * e.g. i was not clear about `country/{id}` page issues
* I would not spend time trying to make tables responsive as there is no easy way to do so
* Re download page: people reading this won't be on phones usually and it is ok that the API part is not responsive

**Comment by anuveyatsu** [comment]
@rufuspollock added some screenshots
