### ISSUE TITLE
Display data for latest week from DB instead of 2nd latest

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#282]
Currently we are displaying data for 2nd latest week from DB. Reason for this was to avoid *not complete weeks* and gray columns in tables until the data arrived for any risk. 

@kxyne says 
> we load the week after the week is complete, so that should be fine.

Since the sourcing team is already loading complete week there is no sense displaying 2nd latest from DB any more  

## Acceptance criteria

- [ ] displaying latest week from DB
- [ ] No gray columns in DB

## Tasks

- [ ] revert latest PR https://github.com/cybergreen-net/stats-new/pull/281
- [ ] switch from month to week
- [ ] updated tests

**Comment by zelima** [comment]
@Kxyne_twitter @chorsley are we really guaranteed that this will be the case? Eg: Right now if you take a look at db there is only 3 entries for latest week.

```
dev=> SELECT * FROM fact_count ORDER BY date DESC limit 6;
    date    | risk | country |  asn  | count | count_amplified 
------------+------+---------+-------+-------+-----------------
 2017-04-17 |    6 | MY      |  9930 |     1 |               0
 2017-04-17 |    6 | IN      |  9829 |     2 |               0
 2017-04-17 |    6 | IN      | 24560 |     1 |               0
 2017-04-16 |    1 | RU      | 60292 |     1 |              41
 2017-04-16 |    1 | US      | 28857 |     1 |              41
 2017-04-16 |    1 | US      | 53785 |     2 |              82
```
There are only 3 entries for `2017-04-17` which is Monday. This would result in map and table like this 
![table](https://cloud.githubusercontent.com/assets/15143785/25431537/1172ed70-2a92-11e7-8cad-4c13fe5f4bc9.png)
![map](https://cloud.githubusercontent.com/assets/15143785/25431538/1174bb50-2a92-11e7-9eaf-91da7d63cb76.png)

**Comment by kxyne** [comment]
We had an error with the automated run test it seems, fixing the data in dev now.

**Comment by zelima** [comment]
@kxyne Is that temporal fix or permanent?
