### ISSUE TITLE
[epic] API Improvements Beta-3

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/stats-new#82]
**These are to be discussed and decided - some may not be beta-3 ...**

- [ ] Additional query options etc - tbd
  - [ ] risk id vs risk name
  - [x] date range options #75 (sort of)
- [ ] Better documentation - tbd
  - risk id and risk name clarifications
  - documentation date field not needed #75 
- [x] CSV output from API #79 
- [ ] API Pagination #73

**Comment by zelima** [comment]
Moving to backlog for now. As needs to properly planed first.

**Comment by zelima** [comment]
Moving to current milestone

**Comment by rufuspollock** [comment]
INVALID out of date epic that is not useful. Have created issues for individual items where relevant.
